// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbtyzloscmhaskjlbyvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRidHl6bG9zY21oYXNramxieXZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNTM3NzAsImV4cCI6MjA3MjkyOTc3MH0.klxb83dKGK6FkdpqkNOBmyIUKKxPilNtl4VqxToe_QU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});